spring.application.name=ghydro

# URL atualizada com o novo IP e o novo nome do banco de dados (bd_ghydro)
spring.datasource.url=jdbc:postgresql://31.97.247.230:5432/bd_ghydro

spring.datasource.username=postgres
# Nova senha configurada
spring.datasource.password=54ffd7ea902a84fb3969

# Boas práticas para evitar erros de versão do driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

api.security.token.secret=£571ZU_m05O%Dv'GJ"RV