spring.application.name=ghydro

# A URL deve seguir o padrão: jdbc:postgresql://ENDPOINT:PORTA/NOME_DO_BANCO
# Estou assumindo que o nome do banco é 'postgres' (padrão do RDS se você não mudou)
spring.datasource.url=jdbc:postgresql://postgress-pi2025.cp2aa4mkiq5u.sa-east-1.rds.amazonaws.com:5432/postgres

spring.datasource.username=postgres
spring.datasource.password=pipi2025

# Boas práticas para evitar erros de versão do driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.mvc.pathmatch.matching-strategy=ant-path-matcher